cloud/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^home/', include('login.urls')),
    url(r'^', include('login.urls')),
    # url(r'^(?P<username>\w+)/', include('upload.urls')),
    url(r'^app/folders/', include('upload.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.conf.urls import url
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'login'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about us/$', views.about_us, name='about_us'),
    url(r'^services/$', views.services, name='services'),
    url(r'^registration/$', views.registration, name='registration'),
    url(r'^activation/',views.activate, name='activation'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^admin/$', views.admin_login, name='admin_login'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^(?P<user_id>[0-9]+)/personal_details/$', views.personal_details, name='personal_details'),
    url(r'^personal_details/update/$', views.personal_details_update, name='personal_details_update'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^delete_account/$', views.delete_account_page, name='delete_account_page'),
    url(r'^(?P<user_id>[0-9]+)/delete_account/$', views.delete_account, name='delete_account'),
]
urlpatterns += staticfiles_urlpatterns()

login/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from .managers import UserManager
from django.conf import settings
import os
import shutil


def folder_directory_path(instance, filename):
    return '{0}/{1}'.format(instance.username, filename)


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(_('username'), max_length=30, blank=False)
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=False)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    date_of_birth = models.DateField(blank=False)
    address = models.CharField(max_length=300, blank=False)
    city = models.CharField(max_length=30, blank=False)
    state = models.CharField(max_length=30, blank=False)
    country = models.CharField(max_length=30, blank=False)
    mobile = models.CharField(max_length=10, blank=False)
    avatar = models.FileField(upload_to=folder_directory_path, null=True, blank=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    password = models.CharField(max_length=300, blank=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name', 'date_of_birth', 'address', 'city', 'state', 'country',
                       'mobile', 'avatar', 'is_active', 'is_superuser', 'is_staff']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name

    def delete(self, *args, **kwargs):
        os.remove(os.path.join(settings.MEDIA_ROOT, self.avatar.name))
        shutil.rmtree(os.path.join(settings.MEDIA_ROOT, self.username))
        super(User, self).delete(*args, **kwargs)

login/forms.py
from django import forms
from .models import User
from django.contrib.admin.widgets import AdminDateWidget


class UserForm(forms.ModelForm):
    date_of_birth = forms.DateField(widget=AdminDateWidget)
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'date_of_birth', 'address', 'city', 'state',
                  'country', 'mobile', 'avatar', 'password', 'confirm_password']


class PersonalDetailsForm(forms.ModelForm):
    date_of_birth = forms.DateField(widget=AdminDateWidget)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'date_of_birth', 'address', 'city', 'state',
                  'country', 'mobile']
        exclude = ['avatar', 'password', 'confirm_password']

login/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from .forms import UserForm, PersonalDetailsForm
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from .models import User
# from django.conf import settings
# import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import socket
socket.getaddrinfo('127.0.0.1', 8000)


def home(request):
    return render(request, 'login/login_form.html')


def about_us(request):
    return render(request, 'login/about_us.html')


def services(request):
    return render(request, 'login/services.html')


def admin_login(request):
    return HttpResponseRedirect('/admin/login/?next=/admin/')


def registration(request):
    form = UserForm(request.POST or None, request.FILES)
    if form.is_valid():
        user = form.save(commit=False)
        email = request.POST['email']
        user.avatar = request.FILES['avatar']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        if password == confirm_password:
            user.set_password(password)
            user.save()
            user = authenticate(email=email, password=password)
            if user is not None:
                user.is_active = False
                # os.mkdir(os.path.join(settings.MEDIA_ROOT, user.username))
                user.save()
                id = user.id
                email = user.email
                send_email(email, id)
                return render(request, 'login/thank_you.html')
            else:
                return render(request, 'login/registration_form.html')
        else:
            msg = 'Password and confirm password does not match. Please try again!'
            context = {
                "msg": msg,
                "form": form,
            }
            return render(request, 'login/registration_form.html', context)
    context = {
        "form": form,
    }
    return render(request, 'login/registration_form.html', context)


def activate(request):
    id = int(request.GET.get('id'))
    user = User.objects.get(id=id)
    user.is_active = True
    user.save()
    return render(request, 'login/activation.html')


def send_email(toaddr, id):
    text = "Greetings!\nYou have successfully registered in Cloud\nPlease click the link below to activate your " \
           "account:\nhttp://127.0.0.1:8000/activation/?id=%s" % id
    part1 = MIMEText(text, 'plain')
    msg = MIMEMultipart('alternative')
    msg.attach(part1)
    subject = "Activate your account at Cloud"
    msg = """\From: %s\nTo: %s\nSubject: %s\n\n%s""" % ('teamcakeshop15@gmail.com', toaddr, subject, msg.as_string())
    server = smtplib.SMTP('smtp.gmail.com:587')
    server.ehlo()
    server.starttls()
    server.login('teamcakeshop15@gmail.com', 'wtfsandy@210')
    server.sendmail('teamcakeshop15@gmail.com', [toaddr], msg)
    server.quit()


def login_user(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(email=email, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/app/folders/')
            else:
                msg = 'Your account has been disabled. Please contact the administrator for further details.'
                context = {
                    "msg": msg,
                }
                return render(request, 'login/login_form.html', context)
        else:
            msg1 = 'Username or Password does not match. Please try again!'
            context = {
                "msg": msg1,
            }
            return render(request, 'login/login_form.html', context)
    return render(request, 'login/login_form.html')


def logout_user(request):
    logout(request)
    return render(request, 'login/login_form.html')


def personal_details(request, user_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        user = request.user
        dp = get_object_or_404(User, pk=user_id)
        context = {
            'avatar': dp,
            'user': user,
        }
        return render(request, 'login/personal_details.html', context)


def delete_account_page(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        return render(request, 'login/delete_account.html')


def delete_account(request, user_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        user = get_object_or_404(User, pk=user_id)
        email = user.email
        account_delete_send_email(email)
        user.delete()
        return render(request, 'login/regret.html')


def account_delete_send_email(toaddr):
    text = "Greetings!\nYou have successfully deleted your Cloud Account\nIf your account is deleted without your " \
           "knowledge please contact our Support Team or Administrator for help.\nThank you for being a loyal user.\n" \
           "Regards\nCloud Support Team\nteamcakeshop15@gmail.com"
    part1 = MIMEText(text, 'plain')
    msg = MIMEMultipart('alternative')
    msg.attach(part1)
    subject = "Delete your account at Cloud"
    msg = """\From: %s\nTo: %s\nSubject: %s\n\n%s""" % ('teamcakeshop15@gmail.com', toaddr, subject, msg.as_string())
    server = smtplib.SMTP('smtp.gmail.com:587')
    server.ehlo()
    server.starttls()
    server.login('teamcakeshop15@gmail.com', 'wtfsandy@210')
    server.sendmail('teamcakeshop15@gmail.com', [toaddr], msg)
    server.quit()


def personal_details_update(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        user = request.user
        data = {
            'username': user.username,
            'email': user.email,
            'first_name': user.first_name,
            'last_name': user.last_name,
            'address': user.address,
            'city': user.city,
            'state': user.state,
            'country': user.country,
            'mobile': user.mobile,
        }
        form = PersonalDetailsForm(request.POST or None, instance=request.user, initial=data)
        if request.method == 'POST':
            if form.is_valid():
                form.save()
                return HttpResponseRedirect('/personal_details/')
            else:
                context = {
                    'form': form,
                }
                return render(request, 'login/personal_details_update.html', context)
        else:
            context = {
                'form': form,
            }
            return render(request, 'login/personal_details_update.html', context)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('login:change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'login/change_password.html', {
        'form': form
    })

templates/login/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title%}Cloud{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'upload/style.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family-satisfy" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand glyphicon glyphicon-cloud" href="{% url 'login:home' %}">Cloud</a>
            </div>

            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="{% block about_us_active %}{% endblock %}">
                        <a href="{% url 'login:about_us' %}">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>&nbsp; About Us
                        </a>
                    </li>
                    <li class="{% block services_active %}{% endblock %}">
                        <a href="{% url 'login:services' %}">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>&nbsp; Services
                        </a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li class="{% block registration_active %}{% endblock %}">
                        <a href="{% url 'login:registration' %}">
                            <span class="glyphicon glyphicon-registration-mark" aria-hidden="true"></span>&nbsp; SignUp For Free
                        </a>
                    </li>
                    <li class="{% block login_user_active %}{% endblock %}">
                        <a href="{% url 'login:login' %}">
                            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; LogIn
                        </a>
                    </li>
                    <li class="{% block login_admin_active %}{% endblock %}">
                        <a href="{% url 'login:admin_login' %}">
                            <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>&nbsp; Admin
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block navigation%}
    {% endblock %}
</body>
</html>

templates/login/delete_account.html
{% extends 'upload/base.html' %}
{% block title %}Cloud | Delete Account{% endblock %}
{% block my_account_active %}active{% endblock %}
{% load staticfiles %}
{% block navigation%}
    <div class="container-fluid">
        <div class="img-thumbnail" style="width: 300px; height: 230px">
            <a href="{% url 'login:personal_details' user.id %}">
                {% if user.avatar %}
                    <img src="{{ user.avatar.url }}" class="img-responsive">
                {% else %}
                    <h3>No image to display</h3>
                {% endif %}
            </a>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="panel panel-default" style="background: transparent; color: black">
                    <div class="panel-body">
                        <div class="row">
                            <h4>Personal Details &nbsp;<a href="{% url 'login:personal_details_update' %}" class="btn-success" style="background: transparent"><span class="glyphicon glyphicon-edit"></span></a></h4><br>
                        </div>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>User Name</th>
                                    <th>Email</th>
                                    <th>First Name</th>
                                    <th>Last Name</th>
                                    <th>Date Of Birth</th>
                                    <th>Address</th>
                                    <th>City</th>
                                    <th>State</th>
                                    <th>Country</th>
                                    <th>Mobile</th>
                                    <th>Account Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>{{ user.username }}</td>
                                    <td>{{ user.email }}</td>
                                    <td>{{ user.first_name }}</td>
                                    <td>{{ user.last_name }}</td>
                                    <td>{{ user.date_of_birth }}</td>
                                    <td>{{ user.address }}</td>
                                    <td>{{ user.city }}</td>
                                    <td>{{ user.state }}</td>
                                    <td>{{ user.country }}</td>
                                    <td>{{ user.mobile }}</td>
                                    <td>
                                        <form action="{% url 'login:delete_account' user.id %}" method="post" style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="user_id" value="{{ user.id }}" />
                                            <button type="submit" class="btn btn-danger btn-xs">
                                                <span class="glyphicon glyphicon-trash"></span>&nbsp; Delete Account
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/login/personal_details_update.html
{% extends 'upload/base.html' %}
{% block title %}Cloud | Personal Details Update{% endblock %}
{% block my_account_active %}active{% endblock %}
{% load staticfiles %}
{% block navigation%}
    <div class="container-fluid files-container">
        <div class="row">
            <div class="col-sm-12 col-md-4">
                <div class="panel panel-default" style="background: transparent">
                    <div class="panel-body">
                        <div class="row">
                            <h4>Personal Details Update Form</h4><br>
                            {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{ error|escape }}</strong>
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">

                            {% csrf_token %}

                            <div class="form-group">
                                <label class="control-label col-sm-4" for="id_username">
                                    Username:
                                </label>
                                {{ form.username }}
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-4" for="id_email">
                                    Email:
                                </label>
                                {{ form.email }}
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-4" for="id_first_name">
                                    First Name:
                                </label>
                                {{ form.first_name }}
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-4" for="id_last_name">
                                    Last Name:
                                </label>
                                {{ form.last_name }}
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-4" for="id_date_of_birth">
                                    Date Of Birth:
                                </label>
                                <div class="ui-widget">
                                    <div class="col-sm-7">
                                        <div class="ui-widget-header">
                                            <input id="id_date_of_birth" name="date_of_birth" type="date" value="{{ user.date_of_birth }}" contenteditable="true"/>
                                        </div>
                                        <div class="ui-widget-content">
                                            <script type="text/javascript" src="{% static 'folders/js/jquery.js' %}"></script>
                                            <script type="text/javascript" src="{% static 'folders/js/jquery-ui.js' %}"></script>
                                            <script type="text/javascript" src="{% static 'folders/js/calendar.js' %}"></script>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-4" for="id_address">
                                    Address:
                                </label>
                                {{ form.address }}
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-4" for="id_city">
                                    City:
                                </label>
                                {{ form.city }}
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-4" for="id_state">
                                    State:
                                </label>
                                {{ form.state }}
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-4" for="id_country">
                                    Country:
                                </label>
                                {{ form.country }}
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-4" for="id_mobile">
                                    Mobile:
                                </label>
                                {{ form.mobile }}
                            </div>

                            <div class="form-group">
                                <div class="col-sm-offset-4">
                                    <button type="submit" class="btn btn-success">Update</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/login/registration_form.html
{% extends 'login/base.html' %}
{% block title %}Cloud | New Registration{% endblock %}
{% block registration_active %}active{% endblock %}
{% block navigation%}
<div class="container-fluid col-sm-10" style="margin-top: 50px; margin-left: 500px;">
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="panel panel-default" style="background: transparent">
                <div class="panel-body">
                    <div class="page-header">
                        {% if msg %}
                            <p><strong><font color="#dc143c">{{ msg }}</font></strong></p>
                        {% endif %}
                    </div>
                    <form class="form-horizontal" role="form" action="{% url 'login:registration' %}" method="post" enctype="multipart/form-data">

                        {% csrf_token %}

                        {{form.non_field_errors}}

                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            <input class="form-control" autofocus="autofocus" placeholder="User Name" id="id_username" type="text" name="username" required/>
                        </div><br>

                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                            <input class="form-control" autofocus="autofocus" placeholder="Email Address" id="id_email" type="email" name="email" required/>
                        </div><br>

                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-king"></i></span>
                            <input class="form-control" autofocus="autofocus" placeholder="First Name" id="id_first_name" type="text" name="first_name" required/>
                        </div><br>

                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-bishop"></i></span>
                            <input class="form-control" autofocus="autofocus" placeholder="Last Name" id="id_last_name" type="text" name="last_name"/>
                        </div><br>

                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                            <input class="form-control" autofocus="autofocus" placeholder="DD-MM-YYYY" id="id_date_of_birth" type="date" name="date_of_birth"/>
                        </div><br>

                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
                            <input class="form-control" autofocus="autofocus" placeholder="Address" id="id_address" type="text" name="address" required/>
                        </div><br>

                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-map-marker"></i></span>
                            <input class="form-control" autofocus="autofocus" placeholder="City Name" id="id_city" type="text" name="city" required/>
                        </div><br>

                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-road"></i></span>
                            <input class="form-control" autofocus="autofocus" placeholder="State Name" id="id_state" type="text" name="state" required/>
                        </div><br>

                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-globe"></i></span>
                            <input class="form-control" autofocus="autofocus" placeholder="Country Name" id="id_country" type="text" name="country" required/>
                        </div><br>

                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
                            <input class="form-control" autofocus="autofocus" placeholder="Mobile" id="id_mobile" type="text" name="mobile" required/>
                        </div><br>

                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-camera"></i></span>
                            <input class="form-control" autofocus="autofocus" placeholder="Avatar (Photo of you)" id="id_avatar" type="file" name="avatar" required/>
                        </div><br>

                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            <input class="form-control" autofocus="autofocus" placeholder="Password" id="id_password" type="password" name="password" required/>
                        </div><br>

                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            <input class="form-control" autofocus="autofocus" placeholder="Re-Type Password Again" id="id_confirm_password" type="password" name="confirm_password" required/>
                        </div><br>

                        <div class="form-group">
                            <div class="col-sm-offset-5">
                                <button type="submit" class="btn btn-success">Register</button>
                            </div>
                        </div>

                    </form>
                </div>
                <div class="panel-footer">
                    Already had an account? <a href="{% url 'login:login' %}">Click here</a> to login.
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}