cloud/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^home/', include('login.urls')),
    url(r'^', include('login.urls')),
    # url(r'^(?P<username>\w+)/', include('upload.urls')),
    url(r'^app/folders/', include('upload.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.conf.urls import url
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'login'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about us/$', views.about_us, name='about_us'),
    url(r'^services/$', views.services, name='services'),
    url(r'^registration/$', views.registration, name='registration'),
    url(r'^activation/',views.activate, name='activation'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^admin/$', views.admin_login, name='admin_login'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^(?P<user_id>[0-9]+)/personal_details/$', views.personal_details, name='personal_details'),
    url(r'^personal_details/update/$', views.personal_details_update, name='personal_details_update'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^delete_account/$', views.delete_account_page, name='delete_account_page'),
    url(r'^(?P<user_id>[0-9]+)/delete_account/$', views.delete_account, name='delete_account'),
]
urlpatterns += staticfiles_urlpatterns()

upload/urls.py
from django.conf.urls import url
from . import views

app_name = 'upload'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_folder/$', views.create_folder, name='folder_add'),
    url(r'^(?P<folder_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<folder_id>[0-9]+)/file_add/$', views.create_file, name='file_add'),
    url(r'^files/(?P<filter_by>[a-zA_Z]+)/$', views.files, name='files'),
    url(r'^(?P<filter_by>[a-zA_Z]+)/$', views.folders, name='folders'),
    url(r'^(?P<folder_id>[0-9]+)/(?P<file_id>[0-9]+)/favorite_file/$', views.favorite_file, name='favorite_file'),
    url(r'^(?P<folder_id>[0-9]+)/update_folder/$', views.update_folder, name='folder_update'),
    url(r'^(?P<folder_id>[0-9]+)/delete_folder/$', views.delete_folder, name='folder_delete'),
    url(r'^(?P<folder_id>[0-9]+)/favorite_folder/$', views.favorite_folder, name='favorite_folder'),
    url(r'^(?P<folder_id>[0-9]+)/delete_file/(?P<file_id>[0-9]+)/$', views.delete_file, name='file_delete'),
    url(r'^delete_file/(?P<file_id>[0-9]+)/$', views.files_delete, name='files_delete'),
    url(r'profile_settings/$', views.profile_settings, name='profile'),
]

upload/models.py
from django.db import models
from django.conf import settings
import os
import shutil


def folder_directory_path(instance, filename):
    return '{0}/{1}/{2}'.format(instance.user.username, instance.folder_name, filename)


def file_directory_path(instance, filename):
    return '{0}/{1}/{2}'.format(instance.user.username, instance.folder.folder_name, filename)


class Folder(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    folder_name = models.CharField(max_length=30, blank=False)
    about_file = models.CharField(max_length=1000)
    folder_image = models.FileField(upload_to=folder_directory_path)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.folder_name

    def __unicode__(self):
        return '%s' % self.folder_name

    def delete(self, *args, **kwargs):
        os.remove(os.path.join(settings.MEDIA_ROOT, self.folder_image.name))
        shutil.rmtree(os.path.join(settings.MEDIA_ROOT, self.user.username, self.folder_name))
        super(Folder, self).delete(*args, **kwargs)


class File(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE)
    file_name = models.CharField(max_length=40, blank=False)
    file = models.FileField(upload_to=file_directory_path, default='Untitled')
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.file_name

    def __unicode__(self):
        return '%s' % self.file.name

    def delete(self, *args, **kwargs):
        os.remove(os.path.join(settings.MEDIA_ROOT, self.file.name))
        super(File, self).delete(*args, **kwargs)

upload/forms.py
from django import forms
from .models import Folder, File


class FileForm(forms.ModelForm):

    class Meta:
        model = File
        fields = ['file_name', 'file']


class FolderForm(forms.ModelForm):

    class Meta:
        model = Folder
        fields = ['folder_name', 'about_file', 'folder_image']

upload/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.db.models import Q
from .forms import FileForm, FolderForm
from .models import Folder, File

AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def create_folder(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        form = FolderForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            folder = form.save(commit=False)
            folder.user = request.user
            folder.folder_image = request.FILES['folder_image']
            file_type = folder.folder_image.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'folder': folder,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'upload/folder_form.html', context)
            folder.save()
            return render(request, 'upload/detail.html', {'folder': folder})
        context = {
            "form": form,
        }
        return render(request, 'upload/folder_form.html', context)


def create_file(request, folder_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        form = FileForm(request.POST or None, request.FILES or None)
        folder = get_object_or_404(Folder, pk=folder_id)
        if form.is_valid():
            folder_files = folder.file_set.all()
            for s in folder_files:
                if s.file_name == form.cleaned_data.get("file_name"):
                    context = {
                        'folder': folder,
                        'form': form,
                        'error_message': 'You already added that file',
                    }
                    return render(request, 'upload/file_form.html', context)
            file = form.save(commit=False)
            file.user = request.user
            file.folder = folder
            file.file = request.FILES['file']
            file_type = file.file.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in AUDIO_FILE_TYPES:
                context = {
                    'folder': folder,
                    'form': form,
                    'error_message': 'Audio file must be WAV, MP3, or OGG',
                }
                return render(request, 'upload/file_form.html', context)

            file.save()
            return render(request, 'upload/detail.html', {'folder': folder})
        context = {
            'folder': folder,
            'form': form,
        }
        return render(request, 'upload/file_form.html', context)


def update_folder(request, folder_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        folder = get_object_or_404(Folder, pk=folder_id)
        if request.POST:
            form = FolderForm(request.POST or None, request.FILES or None, instance=folder)
            if form.is_valid():
                form.folder_image = request.FILES['folder_image']
                file_type = folder.folder_image.url.split('.')[-1]
                file_type = file_type.lower()
                if file_type not in IMAGE_FILE_TYPES:
                    context = {
                        'folder': folder,
                        'form': form,
                        'error_message': 'Image file must be PNG, JPG, or JPEG',
                    }
                    return render(request, 'upload/update_folder.html', context)
                form.save()
                fold = Folder.objects.all()
                context = {
                    "folder": fold
                }
                return render(request, 'upload/index.html', context)
            else:
                folder = Folder.objects.get(pk=folder_id)
                form = FolderForm(request.POST, instance=folder)
                context = {
                    "form": form,
                }
                return render(request, 'upload/update_folder.html', context)


def delete_folder(request, folder_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        folder = get_object_or_404(Folder, pk=folder_id)
        folder.delete()
        fold = Folder.objects.all()
        return render(request, 'upload/index.html', {'folder': fold})


def delete_file(request, folder_id, file_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        folder = get_object_or_404(Folder, pk=folder_id)
        file = File.objects.get(pk=file_id)
        file.delete()
        return render(request, 'upload/detail.html', {'folder': folder})


def files_delete(request, file_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        file = File.objects.get(pk=file_id)
        file.delete()
        fil = File.objects.all()
        return render(request, 'upload/files.html', {'folder_all': fil})


def detail(request, folder_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        user = request.user
        folder = get_object_or_404(Folder, pk=folder_id)
        return render(request, 'upload/detail.html', {'folder': folder, 'user': user})


def index(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        folder = Folder.objects.filter(user=request.user)
        file_results = File.objects.all()
        query = request.GET.get("q")
        if query:
            folder = folder.filter(
                Q(folder_name__icontains=query)
            ).distinct()
            file_results = file_results.filter(
                Q(file_name__icontains=query)
            ).distinct()
            return render(request, 'upload/index.html', {
                'folder': folder,
                'files': file_results,
            })
        return render(request, 'upload/index.html', {'folder': folder})


def files(request, filter_by):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        try:
            file_ids = []
            for folder in Folder.objects.filter(user=request.user):
                for file in folder.file_set.all():
                    file_ids.append(file.pk)
            users_files = File.objects.filter(pk__in=file_ids)
            if filter_by == 'favorites':
                users_files = users_files.filter(is_favorite=True)
        except Folder.DoesNotExist:
            users_files = []
        context = {
            'folder_all': users_files,
            'filter_by': filter_by,
        }
        return render(request, 'upload/files.html', context)


def folders(request, filter_by):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        try:
            folder_ids = []
            for folder in Folder.objects.filter(user=request.user):
                folder_ids.append(folder.pk)
            users_folders = Folder.objects.filter(pk__in=folder_ids)
            if filter_by == 'favorites':
                users_folders = users_folders.filter(is_favorite=True)
        except Folder.DoesNotExist:
            users_folders = []
        context = {
            'folder': users_folders,
            'filter_by': filter_by,
        }
        return render(request, 'upload/folders.html', context)


def profile_settings(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        return render(request, 'upload/profile_settings.html')


def favorite_file(request, folder_id, file_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        file = get_object_or_404(File, pk=file_id)
        if file.is_favorite:
            file.is_favorite = False
        else:
            file.is_favorite = True
        file.save()
        user = request.user
        folder = get_object_or_404(Folder, pk=folder_id)
        return render(request, 'upload/detail.html', {'folder': folder, 'user': user})


def favorite_folder(request, folder_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        folder = get_object_or_404(Folder, pk=folder_id)
        if folder.is_favorite:
            folder.is_favorite = False
        else:
            folder.is_favorite = True
        folder.save()
        return HttpResponseRedirect('/app/folders/')

templates/upload/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title%}Cloud | Home{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family-satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'folders/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand glyphicon glyphicon-cloud" href="{% url 'upload:index' %}">Cloud</a>
            </div>

            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="{% block files_active %}{% endblock %}">
                        <a href="{% url 'upload:files' 'all' %}">
                        <span class="glyphicon glyphicon-file" aria-hidden="true"></span>&nbsp; Files
                        </a>
                    </li>

                    <li class="{% block folder_active %}{% endblock %}">
                        <a href="{% url 'upload:index' %}">
                        <span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>&nbsp; Folders
                        </a>
                    </li>
                </ul>

                <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'upload:index' %}">
                    <div class="input-group">
                        <input type="text" class="input-sm form-control" id="search" placeholder="Search" name="q" value="{{ request.GET.q }}"/>
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                    </div>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li class="{% block add_folder_active %}{% endblock %}">
                        <a href="{% url 'upload:folder_add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Folder
                        </a>
                    </li>

                    <li class="dropdown {% block my_account_active %}{% endblock %}">
                        <a href="{% url 'upload:profile' %}" class="dropdown-toggle" data-toggle="dropdown">Hi, {{ user.first_name }} <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'login:personal_details' user.id %}">Accounts</a></li>
                            <li><a href="{% url 'login:change_password' %}">Change Password</a></li>
                            <li><a href="{% url 'login:delete_account_page' %}">Delete Account</a></li>
                        </ul>
                    </li>

                    <li class="#">
                        <a href="{% url 'login:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
    {% block navigation%}
    {% endblock %}
</body>
</html>

templates/upload/detail.html
{% extends 'upload/base.html' %}
{% block title %}Cloud | {{ folder }}{% endblock %}
{% block folders_active %}active{% endblock %}

{% block navigation%}
<div class="container-fluid files-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default" style="background: transparent">
                <div class="panel-body">
                    <a href="{% url 'upload:detail' folder.id%}">
                        {% if folder.folder_image %}
                            <img src="{{ folder.folder_image.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h3>{{ folder.folder_name }}</h3>
                    <h5 style="color: #255625; font-size: small">{{ folder.about_file }}</h5>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px">
                <li role="presentation" class="active"><a href="{% url 'upload:detail' folder.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'upload:file_add' folder.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default" style="background: transparent; border: transparent">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Song Name</th>
                            <th>Favourite</th>
                            <th>Audio File</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for file in folder.file_set.all %}
                            <tr>
                                <td>{{ file.file_name }}</td>
                                <td>
                                    <a href="{% url 'upload:favorite_file' folder.id file.id %}" class="btn-favorite"><span class="glyphicon glyphicon-heart {% if file.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <a target="_blank" href="{{ file.file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>

                                <td>
                                    <form action="{% url 'upload:file_delete' folder.id file.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="file_id" value="{{ file.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

templates/upload/folder_form.html
{% extends 'upload/base.html' %}
{% block title %}Cloud | Add New Folder{% endblock %}
{% block add_folder_active %}active{% endblock %}

{% block navigation %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-4">
            <div class="panel panel-default" style="background: transparent">
                <div class="panel-body">
                    <h3>Add a New Folder</h3>
                    {% if error_message %}
                        <p><strong><font color="#dc143c">{{ error_message }}</font></strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'upload/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-4 col-sm-10">
                                <button type="submit" class="btn btn-success">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/upload/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-4 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-4">{{ field.label_tag }}</label>
        <div class="col-sm-7">{{ field }}</div>
    </div>
{% endfor %}

templates/upload/index.html
{% extends 'upload/base.html' %}
{% block title %}Cloud | All Folders{% endblock %}
{% block folder_active %}active{% endblock %}
{% block navigation%}
<div class="folders-container container-fluid">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == 'favorites' %}class="active" {% endif %}><a href="{% url 'upload:folders' 'favorites' %}">View Favorites</a></li>
            </ul>
        </div>
    </div>

    <!-- Folders -->
    <div class="row">

        {% if folder %}
            {% for folder in folder %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail" style="background: transparent">
                        <a href="{% url 'upload:detail' folder.id %}">
                            <img src="{{ folder.folder_image.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h3><!-- Favorite Album -->
                            <a style="background: transparent; border: transparent" href="{% url 'upload:favorite_folder' folder.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-heart {% if folder.is_favorite %}active{% endif %}"></span>
                            </a>{{ folder.folder_name }}</h3>

                            <!-- View Details -->
                            <a href="{% url 'upload:detail' folder.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Folder -->
                            <form action="{% url 'upload:folder_delete' folder.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="folder_id" value="{{ folder.id }}" />
                                <button type="submit" class="btn btn-danger btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Update Folder -->
                            <form action="{% url 'upload:folder_update' folder.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="folder_id" value="{{ folder.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-edit"></span>
                                </button>
                            </form>



                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12 {% block add_folder_active %}{% endblock %}">
                <br>
                <a href="{% url 'upload:folder_add' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Folder
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are files -->

    {% if files %}
        <div class="row">
            <div class="col-sm-12">
                <h3><small><font color="black">Files</font></small></h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default" style="background: transparent; border: transparent">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Name</th>
                                    <th>Favourite</th>
                                    <th>Audio File</th>
                                    <th>Actions</th>
                                    <th>Folder</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if folder %}
                                    {% for folder in folder %}
                                        {% for file in files %}
                                            <tr>
                                                <td>{{ file.file_name }}</td>
                                                <td>
                                                    <a href="{% url 'upload:favorite_file' file.folder.id file.id %}" class="btn-favorite"><span class="glyphicon glyphicon-heart {% if file.is_favorite %}active{% endif %}"></span></a>
                                                </td>
                                                <td>
                                                    <a target="_blank" href="{{ file.audio_file.url }}">
                                                        <button type="button" class="btn btn-success btn-xs">
                                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                        </button>
                                                    </a>
                                                </td>
                                                <td>
                                                    <form action="{% url 'upload:file_delete' folder.id file.id %}" method="post" style="display: inline;">
                                                        {% csrf_token %}
                                                        <input type="hidden" name="folder_id" value="{{ folder.id }}" />
                                                        <input type="hidden" name="file_id" value="{{ file.id }}" />
                                                        <button type="submit" class="btn btn-danger btn-xs">
                                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                                        </button>
                                                    </form>
                                                </td>
                                                <td>
                                                    <a href="{% url 'upload:detail' file.folder.id %}">
                                                        <img src="{{ file.folder.folder_image.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                                    </a>
                                                    <a href="{% url 'upload:detail' file.folder.id %}">{{ file.folder.folder_name }}</a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    {% endfor %}
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

templates/upload/profile_settings.html
{% extends 'upload/base.html' %}
{% block title %}Cloud | Profile{% endblock %}
{% block folders_active %}active{% endblock %}

{% block navigation%}
{% endblock %}